export { default as Bell } from "./bell.svg";
export { default as Email } from "./email.svg";
export { default as Egypt } from "./egypt-flag.svg";
export {default as  FacebookIcon } from "./facebook.svg";
export { default as GoogleIcon } from "./google.svg";
export { default as Arrow } from "./arrow.svg";
export { default as HideEye } from "./hide.svg";
export { default as MandatoryIcon } from "./mandatory.svg";
export { default as ShowEye } from "./show.svg";
export { default as Password } from "./password.svg";
export { default as ProfileUser } from './user.svg';
export { default as VoloroLogo } from './valoro-logo.svg';
export { default as Check } from './check.svg';
